"""Reader for Spark Performance Gold tables.

Reads pre-computed Gold tables generated by the spark-perf-job ETL
notebooks. These tables live in a separate schema from the DBSQL
profiler tables and have a configurable table prefix.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class SparkPerfConfig:
    """Configuration for Spark Performance table reader."""

    catalog: str
    schema: str
    table_prefix: str
    databricks_host: str
    databricks_token: str
    http_path: str

    @classmethod
    def from_env(cls) -> SparkPerfConfig:
        """Load configuration from config file + environment variables."""
        from core.config_store import get_setting

        return cls(
            catalog=get_setting("spark_perf_catalog", "main"),
            schema=get_setting("spark_perf_schema", "default"),
            table_prefix=get_setting("spark_perf_table_prefix", "PERF_"),
            databricks_host=os.environ.get("DATABRICKS_HOST", ""),
            databricks_token=os.environ.get("DATABRICKS_TOKEN", ""),
            http_path=get_setting("spark_perf_http_path", ""),
        )


class SparkPerfReader:
    """Reads Spark Performance Gold tables from Delta."""

    def __init__(self, config: SparkPerfConfig) -> None:
        self._config = config

    def _fqn(self, table_suffix: str) -> str:
        """Return fully-qualified table name with prefix (validated)."""
        from core.sql_safe import safe_fqn

        table_name = f"{self._config.table_prefix}{table_suffix}"
        return safe_fqn(self._config.catalog, self._config.schema, table_name)

    @staticmethod
    def _strip_host(raw: str) -> str:
        """Remove scheme and trailing slash from a hostname."""
        h = raw
        if h.startswith("https://"):
            h = h[len("https://") :]
        if h.startswith("http://"):
            h = h[len("http://") :]
        return h.rstrip("/")

    def _get_connection(self) -> Any:
        """Get SQL connection using SP credentials."""
        from . import get_sp_sql_connection

        return get_sp_sql_connection(self._config.http_path)

    # ------------------------------------------------------------------
    # Query helpers
    # ------------------------------------------------------------------

    def _query_table(self, table_suffix: str, app_id: str | None = None) -> list[dict[str, Any]]:
        """Query a Gold table and return rows as list of dicts."""
        fqn = self._fqn(table_suffix)
        where = ""
        params: dict[str, Any] = {}
        if app_id:
            where = "WHERE app_id = :app_id"
            params["app_id"] = app_id

        sql = f"SELECT * FROM {fqn} {where}"
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parameters=params if params else None)
                    columns = [desc[0] for desc in cursor.description]
                    rows = cursor.fetchall()
                    return [dict(zip(columns, row)) for row in rows]
        except Exception:
            logger.exception("Failed to query %s", fqn)
            return []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def get_application_summary(self, app_id: str) -> dict[str, Any] | None:
        """Get application summary for a given app_id."""
        rows = self._query_table("gold_application_summary", app_id=app_id)
        return rows[0] if rows else None

    def get_bottleneck_report(self, app_id: str) -> list[dict[str, Any]]:
        """Get bottleneck report for a given app_id."""
        return self._query_table("gold_bottleneck_report", app_id=app_id)

    def get_stage_performance(self, app_id: str) -> list[dict[str, Any]]:
        """Get stage performance for a given app_id."""
        return self._query_table("gold_stage_performance", app_id=app_id)

    def get_executor_analysis(self, app_id: str) -> list[dict[str, Any]]:
        """Get executor analysis for a given app_id."""
        return self._query_table("gold_executor_analysis", app_id=app_id)

    def get_job_concurrency(self, app_id: str) -> list[dict[str, Any]]:
        """Get job concurrency analysis for a given app_id."""
        return self._query_table("gold_job_concurrency", app_id=app_id)

    def get_sql_photon_analysis(self, app_id: str) -> list[dict[str, Any]]:
        """Get SQL/Photon analysis for a given app_id."""
        return self._query_table("gold_sql_photon_analysis", app_id=app_id)

    def get_spark_config_analysis(self, app_id: str) -> list[dict[str, Any]]:
        """Get Spark config analysis for a given app_id."""
        return self._query_table("gold_spark_config_analysis", app_id=app_id)

    def get_job_performance(self, app_id: str) -> list[dict[str, Any]]:
        """Get job performance for a given app_id."""
        return self._query_table("gold_job_performance", app_id=app_id)

    def get_spot_instance_analysis(self, app_id: str) -> list[dict[str, Any]]:
        """Get spot instance / node loss analysis for a given app_id."""
        return self._query_table("gold_spot_instance_analysis", app_id=app_id)

    def get_autoscale_timeline(self, app_id: str) -> list[dict[str, Any]]:
        """Get autoscale timeline (executor scaling correlated with stages)."""
        return self._query_table("gold_autoscale_timeline", app_id=app_id)

    def get_job_detail(self, app_id: str) -> list[dict[str, Any]]:
        """Get job detail (stages per job) for a given app_id."""
        return self._query_table("gold_job_detail", app_id=app_id)

    def get_cross_app_concurrency(self, app_id: str) -> list[dict[str, Any]]:
        """Get cross-app concurrency data for a given app_id."""
        return self._query_table("gold_cross_app_concurrency", app_id=app_id)

    # ------------------------------------------------------------------
    # Composite queries (for LLM Fact Pack assembly)
    # ------------------------------------------------------------------

    def get_io_summary(self, app_id: str) -> dict[str, float]:
        """Aggregate I/O metrics from stage performance data."""
        stages = self.get_stage_performance(app_id)
        total_input = sum(float(s.get("input_mb", 0) or 0) for s in stages) / 1024
        total_output = sum(float(s.get("output_mb", 0) or 0) for s in stages) / 1024
        total_shuffle_read = sum(float(s.get("shuffle_read_mb", 0) or 0) for s in stages) / 1024
        total_shuffle_write = sum(float(s.get("shuffle_write_mb", 0) or 0) for s in stages) / 1024
        total_disk_spill = sum(float(s.get("disk_spill_mb", 0) or 0) for s in stages) / 1024
        total_memory_spill = sum(float(s.get("memory_spill_mb", 0) or 0) for s in stages) / 1024
        return {
            "total_input_gb": round(total_input, 2),
            "total_output_gb": round(total_output, 2),
            "total_shuffle_read_gb": round(total_shuffle_read, 2),
            "total_shuffle_write_gb": round(total_shuffle_write, 2),
            "total_disk_spill_gb": round(total_disk_spill, 2),
            "total_memory_spill_gb": round(total_memory_spill, 2),
        }

    def get_bottleneck_summary(self, app_id: str) -> list[dict[str, Any]]:
        """Aggregate bottleneck counts by type and severity."""
        bottlenecks = self.get_bottleneck_report(app_id)
        summary: dict[str, dict] = {}
        for b in bottlenecks:
            bt = b.get("bottleneck_type", "UNKNOWN")
            sev = b.get("severity", "UNKNOWN")
            dur = float(b.get("duration_ms", 0) or 0)
            if bt not in summary:
                summary[bt] = {
                    "bottleneck_type": bt,
                    "count": 0,
                    "total_duration_ms": 0,
                    "max_severity": sev,
                }
            summary[bt]["count"] += 1
            summary[bt]["total_duration_ms"] += dur
            # Track max severity
            sev_rank = {"CRITICAL": 4, "HIGH": 3, "MEDIUM": 2, "LOW": 1}
            if sev_rank.get(sev, 0) > sev_rank.get(summary[bt]["max_severity"], 0):
                summary[bt]["max_severity"] = sev
        return list(summary.values())

    def get_concurrency_summary(self, app_id: str) -> dict[str, Any]:
        """Summarize concurrency statistics (no per-job detail)."""
        concurrency = self.get_job_concurrency(app_id)
        cross_app = self.get_cross_app_concurrency(app_id)

        # Cross-app summary (independent of intra-app concurrency)
        cross_app_detected = (
            sum(1 for c in cross_app if int(c.get("cross_app_concurrent_count", 0) or 0) > 0)
            if cross_app
            else 0
        )

        if not concurrency:
            # Still return cross-app info even if intra-app data is empty
            if cross_app_detected > 0:
                return {"total_jobs": 0, "cross_app_jobs_detected": cross_app_detected}
            return {}

        total_jobs = len(concurrency)
        concurrent_vals = [int(c.get("concurrent_jobs_at_start", 0) or 0) for c in concurrency]
        max_concurrent = max(concurrent_vals) if concurrent_vals else 0
        jobs_with_concurrency = sum(1 for v in concurrent_vals if v > 0)

        # CPU efficiency comparison: concurrent vs solo
        concurrent_cpu = [
            float(c.get("cpu_efficiency_pct", 0) or 0)
            for c in concurrency
            if int(c.get("concurrent_jobs_at_start", 0) or 0) > 0
        ]
        solo_cpu = [
            float(c.get("cpu_efficiency_pct", 0) or 0)
            for c in concurrency
            if int(c.get("concurrent_jobs_at_start", 0) or 0) == 0
        ]
        avg_concurrent_cpu = (
            round(sum(concurrent_cpu) / len(concurrent_cpu), 1) if concurrent_cpu else None
        )
        avg_solo_cpu = round(sum(solo_cpu) / len(solo_cpu), 1) if solo_cpu else None

        result: dict[str, Any] = {
            "total_jobs": total_jobs,
            "max_concurrent_jobs": max_concurrent,
            "jobs_with_concurrency": jobs_with_concurrency,
            "cross_app_jobs_detected": cross_app_detected,
        }
        if avg_concurrent_cpu is not None:
            result["avg_cpu_concurrent_pct"] = avg_concurrent_cpu
        if avg_solo_cpu is not None:
            result["avg_cpu_solo_pct"] = avg_solo_cpu
        if avg_concurrent_cpu is not None and avg_solo_cpu is not None:
            # Negative = concurrent is worse than solo (degradation)
            result["cpu_diff_pp"] = round(avg_concurrent_cpu - avg_solo_cpu, 1)
            result["cpu_diff_interpretation"] = (
                "negative means concurrent jobs have lower CPU efficiency (degradation)"
            )
        return result

    def get_executor_summary(self, app_id: str) -> dict[str, Any]:
        """Aggregate executor metrics into a diagnosis summary (no per-executor detail)."""
        executors = self.get_executor_analysis(app_id)
        if not executors:
            return {}

        n = len(executors)

        def _vals(key: str) -> tuple[list[float], bool]:
            """Extract non-None float values. Returns (values, has_data)."""
            raw = [e.get(key) for e in executors]
            vals = [float(v) for v in raw if v is not None]
            return vals, len(vals) > 0

        cpu_effs, cpu_has_data = _vals("cpu_efficiency_pct")
        gc_pcts, gc_has_data = _vals("gc_overhead_pct")
        disk_spills, _ = _vals("disk_spill_mb")
        mem_spills, _ = _vals("memory_spill_mb")
        ser_pcts, ser_has_data = _vals("serialization_pct")

        # Diagnosis counts
        diag_counts: dict[str, int] = {}
        for e in executors:
            diag = e.get("resource_diagnosis", "")
            if diag:
                for d in str(diag).split(","):
                    d = d.strip()
                    if d:
                        diag_counts[d] = diag_counts.get(d, 0) + 1

        stragglers = [e for e in executors if e.get("is_straggler") in (True, "YES", "true", 1)]
        underutilized = [e for e in executors if float(e.get("load_vs_avg", 1) or 1) < 0.3]
        spill_execs = [e for e in executors if float(e.get("disk_spill_mb", 0) or 0) > 0]

        # Memory config from first executor
        first = executors[0]
        result: dict[str, Any] = {
            "executor_count": n,
            "total_cores": first.get("total_cores"),
            "executor_memory_mb": first.get("executor_memory_mb"),
            "offheap_size_mb": first.get("offheap_size_mb"),
            "total_disk_spill_mb": round(sum(disk_spills), 0),
            "total_memory_spill_mb": round(sum(mem_spills), 0),
            "executors_with_spill": len(spill_execs),
            "diagnosis_counts": diag_counts,
            "straggler_count": len(stragglers),
            "underutilized_count": len(underutilized),
        }
        # CPU efficiency: distinguish "0%" from "no data"
        if cpu_has_data:
            result["avg_cpu_efficiency_pct"] = round(sum(cpu_effs) / len(cpu_effs), 1)
            result["cpu_efficiency_range"] = f"{min(cpu_effs):.1f}% - {max(cpu_effs):.1f}%"
        else:
            result["avg_cpu_efficiency_pct"] = None
            result["cpu_efficiency_note"] = "no data recorded"
        # GC
        if gc_has_data:
            result["avg_gc_pct"] = round(sum(gc_pcts) / len(gc_pcts), 1)
            result["gc_range"] = f"{min(gc_pcts):.1f}% - {max(gc_pcts):.1f}%"
        else:
            result["avg_gc_pct"] = None
            result["gc_note"] = "no data recorded"
        # Serialization
        if ser_has_data:
            result["avg_serialization_pct"] = round(sum(ser_pcts) / len(ser_pcts), 1)
        else:
            result["avg_serialization_pct"] = None
            result["serialization_note"] = "no data recorded"
        return result

    def get_autoscale_cost_summary(self, app_id: str) -> list[dict[str, Any]]:
        """Summarize what % of time was spent at each worker count.

        Clips events to the app's [start_ts, end_ts] window so that
        post-termination executor events (driver shutdown, cluster idle,
        other apps on shared clusters) do not inflate the distribution.
        Extends the final event to end_ts to capture the steady state
        at max worker count (which the event timeline does not record
        explicitly).
        """
        from datetime import datetime

        timeline = self.get_autoscale_timeline(app_id)
        if not timeline:
            return []

        def _parse(raw: Any) -> datetime | None:
            if not raw:
                return None
            for fmt in (
                "%Y-%m-%dT%H:%M:%S.%f",
                "%Y-%m-%d %H:%M:%S.%f",
                "%Y-%m-%dT%H:%M:%S",
                "%Y-%m-%d %H:%M:%S",
            ):
                try:
                    return datetime.strptime(str(raw)[:26], fmt)
                except (ValueError, TypeError):
                    continue
            return None

        # Fetch app window
        app = self.get_application_summary(app_id) or {}
        start_ts = _parse(app.get("start_ts"))
        end_ts = _parse(app.get("end_ts"))

        # Parse and sort events
        events: list[tuple[datetime, int]] = []
        for row in timeline:
            ts = _parse(row.get("event_ts"))
            if ts is None:
                continue
            wc = int(row.get("worker_count_after", 0) or 0)
            events.append((ts, wc))
        events.sort()

        # Clip events to [start_ts, end_ts] window
        if start_ts and end_ts:
            events = [(ts, wc) for ts, wc in events if start_ts <= ts <= end_ts]
            # Synthetic end event so steady state at last wc is counted
            if events and events[-1][0] < end_ts:
                events.append((end_ts, events[-1][1]))

        # Aggregate durations at each worker count
        worker_time: dict[int, float] = {}
        prev_ts: datetime | None = None
        prev_wc = 0
        for ts, wc in events:
            if prev_ts is not None:
                dur = (ts - prev_ts).total_seconds()
                if dur > 0:
                    worker_time[prev_wc] = worker_time.get(prev_wc, 0) + dur
            prev_ts = ts
            prev_wc = wc

        total_sec = sum(worker_time.values())
        return [
            {
                "worker_count": wc,
                "cumulative_min": round(t / 60, 1),
                "pct_of_total": round(t / total_sec * 100, 1) if total_sec > 0 else 0,
            }
            for wc, t in sorted(worker_time.items())
        ]

    def get_scaling_event_counts(self, app_id: str) -> dict[str, int]:
        """Count scaling/removal events by type (Autoscale, Spot, Node Loss, etc.)."""
        timeline = self.get_autoscale_timeline(app_id)
        spot_data = self.get_spot_instance_analysis(app_id)

        counts: dict[str, int] = {
            "SCALE_OUT": 0,
            "AUTOSCALE_IN": 0,
            "CLUSTER_SHUTDOWN": 0,
            "SPOT_PREEMPTION": 0,
            "NODE_LOST": 0,
            "OTHER_REMOVAL": 0,
        }

        for row in timeline:
            event_type = row.get("event_type", "")
            reason = (row.get("event_reason") or "").upper()

            if event_type == "EXECUTOR_ADDED":
                counts["SCALE_OUT"] += 1
            elif event_type == "EXECUTOR_REMOVED":
                if "AUTOSCALE" in reason:
                    counts["AUTOSCALE_IN"] += 1
                elif "CLUSTER" in reason or "SHUTDOWN" in reason or "STOP" in reason:
                    counts["CLUSTER_SHUTDOWN"] += 1
                elif "SPOT" in reason or "PREEMPTION" in reason:
                    counts["SPOT_PREEMPTION"] += 1
                elif "NODE" in reason or "LOST" in reason or "HEARTBEAT" in reason:
                    counts["NODE_LOST"] += 1
                else:
                    counts["OTHER_REMOVAL"] += 1

        # Cross-check with spot table for unexpected losses
        unexpected_losses = sum(
            1 for s in spot_data if s.get("is_unexpected_loss") in (True, "true", "YES", 1)
        )
        if unexpected_losses > counts["SPOT_PREEMPTION"] + counts["NODE_LOST"]:
            counts["NODE_LOST"] = unexpected_losses

        # Remove zero-count entries for cleaner output
        return {k: v for k, v in counts.items() if v > 0}

    def get_spark_config_changed(self, app_id: str) -> list[dict[str, Any]]:
        """Get Spark config entries that differ from defaults."""
        configs = self.get_spark_config_analysis(app_id)
        return [c for c in configs if c.get("is_changed") in ("YES", "SET")]

    def get_aqe_diagnosis(self, app_id: str) -> dict[str, Any]:
        """Diagnose AQE utilization: config state, skew detection, partition sizing, join balance.

        Returns empty dict if no config data available.
        """
        configs = self.get_spark_config_analysis(app_id)
        if not configs:
            return {}

        # Extract AQE-related configs
        _AQE_KEYS = {
            "spark.sql.adaptive.enabled",
            "spark.sql.adaptive.coalescePartitions.enabled",
            "spark.sql.adaptive.coalescePartitions.minPartitionNum",
            "spark.sql.adaptive.skewJoin.enabled",
            "spark.sql.adaptive.skewJoin.skewedPartitionFactor",
            "spark.sql.adaptive.skewJoin.skewedPartitionThresholdInBytes",
            "spark.sql.adaptive.advisoryPartitionSizeInBytes",
            "spark.sql.shuffle.partitions",
            "spark.sql.autoBroadcastJoinThreshold",
        }
        aqe_configs: list[dict[str, str]] = []
        for c in configs:
            key = c.get("config_key", "")
            if key in _AQE_KEYS:
                aqe_configs.append(
                    {
                        "key": key,
                        "actual": c.get("actual_value", ""),
                        "default": c.get("default_value", ""),
                        "is_changed": c.get("is_changed", "NO"),
                    }
                )

        if not aqe_configs:
            return {}

        # Build config lookup
        cfg = {c["key"]: c["actual"] for c in aqe_configs}

        aqe_enabled = cfg.get("spark.sql.adaptive.enabled", "true").lower() == "true"
        coalesce_enabled = (
            cfg.get("spark.sql.adaptive.coalescePartitions.enabled", "true").lower() == "true"
        )
        skew_join_enabled = cfg.get("spark.sql.adaptive.skewJoin.enabled", "true").lower() == "true"

        # Get bottleneck and join data for context
        bn_summary = self.get_bottleneck_summary(app_id)
        skew_count = sum(
            int(b.get("count", 0)) for b in bn_summary if b.get("bottleneck_type") == "DATA_SKEW"
        )
        shuffle_count = sum(
            int(b.get("count", 0))
            for b in bn_summary
            if b.get("bottleneck_type") == "HEAVY_SHUFFLE"
        )

        sql_photon = self.get_sql_photon_analysis(app_id)
        total_smj = sum(int(s.get("smj_count", 0) or 0) for s in sql_photon)
        total_bhj = sum(
            int(s.get("bhj_count", 0) or 0) + int(s.get("photon_bhj_count", 0) or 0)
            for s in sql_photon
        )

        # Recommendations
        recommendations: list[str] = []
        if not aqe_enabled:
            recommendations.append("spark.sql.adaptive.enabled=true を有効化（AQE全体が無効）")
        if skew_count > 0 and not skew_join_enabled:
            recommendations.append(
                "spark.sql.adaptive.skewJoin.enabled=true を有効化（DATA_SKEWステージあり）"
            )
        if skew_count > 0 and skew_join_enabled:
            factor = cfg.get("spark.sql.adaptive.skewJoin.skewedPartitionFactor", "5")
            if factor and int(factor) >= 5:
                recommendations.append(
                    f"skewedPartitionFactor={factor} → 3に下げてSkew検出感度を向上"
                )
        if shuffle_count > 0:
            partitions = cfg.get("spark.sql.shuffle.partitions", "200")
            recommendations.append(
                f"shuffle.partitions={partitions}、HEAVY_SHUFFLEステージあり。advisoryPartitionSizeInBytesの調整を検討"
            )
        if total_smj > 3 and total_bhj == 0:
            recommendations.append(
                f"SortMergeJoin {total_smj}件、BroadcastHashJoin 0件。autoBroadcastJoinThresholdの引上を検討"
            )

        return {
            "aqe_configs": aqe_configs,
            "aqe_enabled": aqe_enabled,
            "coalesce_enabled": coalesce_enabled,
            "skew_join_enabled": skew_join_enabled,
            "data_skew_stages": skew_count,
            "heavy_shuffle_stages": shuffle_count,
            "total_smj": total_smj,
            "total_bhj": total_bhj,
            "recommendations": recommendations,
        }

    def get_scaling_quality(self, app_id: str) -> dict[str, Any]:
        """Diagnose dynamic allocation quality: scaling delays, over/under-provisioning.

        Returns empty dict if no autoscale timeline data.
        """
        timeline = self.get_autoscale_timeline(app_id)
        if not timeline:
            return {}

        autoscale_cost = self.get_autoscale_cost_summary(app_id)
        executor_summary = self.get_executor_summary(app_id)
        scaling_events = self.get_scaling_event_counts(app_id)
        app_summary = self.get_application_summary(app_id) or {}

        max_workers = int(app_summary.get("max_workers", 0) or 0)
        min_workers = int(app_summary.get("min_workers", 0) or 0)
        duration_min = float(app_summary.get("duration_min", 0) or 0)
        avg_cpu = (
            float(executor_summary.get("avg_cpu_efficiency_pct", 0) or 0) if executor_summary else 0
        )

        # Initial scale delay: time from first event to first worker available
        first_event = timeline[0] if timeline else {}
        initial_delay_sec = 0
        if first_event.get("event_type") == "EXECUTOR_ADDED":
            initial_delay_sec = int(first_event.get("segment_duration_sec", 0) or 0)

        # Scale-out speed: time from 1st worker to reaching max
        scale_events = [t for t in timeline if t.get("event_type") == "EXECUTOR_ADDED"]
        max_reached = (
            max(int(t.get("worker_count_after", 0) or 0) for t in timeline) if timeline else 0
        )
        scale_out_duration_sec = 0
        if len(scale_events) >= 2:
            # Sum segment durations during scale-out phase
            for t in scale_events[1:]:
                wc = int(t.get("worker_count_after", 0) or 0)
                if wc <= max_reached:
                    scale_out_duration_sec += int(t.get("segment_duration_sec", 0) or 0)

        # Time at max workers (from autoscale_cost)
        time_at_max_pct = 0.0
        if autoscale_cost and max_workers > 0:
            for entry in autoscale_cost:
                if int(entry.get("worker_count", 0)) >= max_workers:
                    time_at_max_pct += float(entry.get("pct_of_total", 0))

        # Time at min workers
        time_at_min_pct = 0.0
        if autoscale_cost and min_workers >= 0:
            for entry in autoscale_cost:
                if int(entry.get("worker_count", 0)) <= max(min_workers, 1):
                    time_at_min_pct += float(entry.get("pct_of_total", 0))

        # Over/under-provisioning detection
        overprovisioned = time_at_max_pct > 60 and avg_cpu < 50
        underprovisioned = time_at_max_pct > 80 and avg_cpu > 80

        # Idle periods: segments with 0 active stages
        idle_segments = [
            t
            for t in timeline
            if int(t.get("active_stage_count", 0) or 0) == 0
            and int(t.get("segment_duration_sec", 0) or 0) > 10
        ]
        idle_total_sec = sum(int(t.get("segment_duration_sec", 0) or 0) for t in idle_segments)

        # Recommendations
        recommendations: list[str] = []
        if initial_delay_sec > 60:
            recommendations.append(
                f"初回スケールアウトに{initial_delay_sec}秒。min_workersの引上またはウォームプール設定を検討"
            )
        if overprovisioned:
            recommendations.append(
                f"実行時間の{time_at_max_pct:.0f}%がmax_workers到達だがCPU効率{avg_cpu:.0f}%。"
                "max_workersの引下またはインスタンスサイズ縮小を検討"
            )
        if underprovisioned:
            recommendations.append(
                f"実行時間の{time_at_max_pct:.0f}%がmax_workers到達でCPU効率{avg_cpu:.0f}%。"
                "max_workersの引上を検討"
            )
        if idle_total_sec > duration_min * 60 * 0.2 and idle_total_sec > 60:
            recommendations.append(
                f"アイドル時間{idle_total_sec}秒（アクティブステージなし）。"
                "ジョブ分割またはmin_workersの引下を検討"
            )
        scale_out_count = int(scaling_events.get("SCALE_OUT", 0))
        scale_in_count = int(scaling_events.get("AUTOSCALE_IN", 0))
        if scale_out_count + scale_in_count > 20:
            recommendations.append(
                f"スケーリングイベント{scale_out_count + scale_in_count}回（OUT:{scale_out_count} IN:{scale_in_count}）。"
                "頻繁なスケーリングはオーバーヘッド。min/max_workersの範囲を狭めることを検討"
            )

        return {
            "initial_scale_delay_sec": initial_delay_sec,
            "scale_out_duration_sec": scale_out_duration_sec,
            "max_workers_reached": max_reached,
            "time_at_max_pct": round(time_at_max_pct, 1),
            "time_at_min_pct": round(time_at_min_pct, 1),
            "avg_cpu_at_max": round(avg_cpu, 1),
            "overprovisioned": overprovisioned,
            "underprovisioned": underprovisioned,
            "idle_periods": len(idle_segments),
            "idle_total_sec": idle_total_sec,
            "scaling_events": scaling_events,
            "recommendations": recommendations,
        }

    def get_memory_analysis(self, app_id: str) -> dict[str, Any]:
        """Analyze memory configuration and utilization efficiency.

        Returns empty dict if no executor or config data available.
        """
        executor_summary = self.get_executor_summary(app_id)
        if not executor_summary:
            return {}

        configs = self.get_spark_config_analysis(app_id)
        if not configs:
            return {}

        # Extract memory configs
        cfg: dict[str, str] = {}
        for c in configs:
            key = c.get("config_key", "")
            if (
                "memory" in key.lower()
                or "heap" in key.lower()
                or "fraction" in key.lower()
                or "storage" in key.lower()
            ):
                cfg[key] = c.get("actual_value", "")

        onheap_mb = float(executor_summary.get("executor_memory_mb") or 0)
        offheap_mb = float(executor_summary.get("offheap_size_mb") or 0)
        total_mb = onheap_mb + offheap_mb

        if total_mb <= 0:
            return {}

        # Parse memory fractions
        fraction = float(cfg.get("spark.memory.fraction", "0.6") or 0.6)
        storage_fraction = float(cfg.get("spark.memory.storageFraction", "0.5") or 0.5)
        offheap_enabled = cfg.get("spark.memory.offHeap.enabled", "false").lower() == "true"

        # Calculated allocations
        unified_mb = round(onheap_mb * fraction, 0)
        storage_mb = round(unified_mb * storage_fraction, 0)
        execution_mb = round(unified_mb * (1 - storage_fraction), 0)
        user_mb = round(onheap_mb * (1 - fraction), 0)

        # Utilization from executor data
        exec_count = int(executor_summary.get("executor_count", 0) or 0)
        total_spill = float(executor_summary.get("total_disk_spill_mb", 0) or 0)
        avg_gc = float(executor_summary.get("avg_gc_pct") or 0)
        spill_execs = int(executor_summary.get("executors_with_spill", 0) or 0)

        # Recommendations
        recommendations: list[str] = []
        if total_spill > 1000:
            recommendations.append(
                f"ディスクスピル合計{total_spill:.0f} MB。Executionメモリ（{execution_mb:.0f} MB）が不足。"
                "spark.memory.fractionの引上またはインスタンスサイズ増を検討"
            )
        if avg_gc > 15:
            recommendations.append(
                f"GCオーバーヘッド{avg_gc:.1f}%。On-heapメモリ（{onheap_mb:.0f} MB）に対するオブジェクト圧が高い。"
                "spark.executor.memoryの増加を検討"
            )
        if offheap_enabled and offheap_mb > onheap_mb * 2:
            recommendations.append(
                f"Off-heap（{offheap_mb:.0f} MB）がOn-heap（{onheap_mb:.0f} MB）の{offheap_mb / onheap_mb:.1f}倍。"
                "Photon/Tungsten向けの構成。On-heap不足に注意"
            )
        if total_spill == 0 and avg_gc < 5 and onheap_mb > 8000:
            recommendations.append(
                f"スピルなし、GC {avg_gc:.1f}%。メモリに余裕あり。インスタンスサイズダウンでコスト削減の余地"
            )

        return {
            "onheap_mb": round(onheap_mb, 0),
            "offheap_mb": round(offheap_mb, 0),
            "total_mb": round(total_mb, 0),
            "unified_mb": unified_mb,
            "storage_mb": storage_mb,
            "execution_mb": execution_mb,
            "user_mb": user_mb,
            "memory_fraction": fraction,
            "storage_fraction": storage_fraction,
            "offheap_enabled": offheap_enabled,
            "executor_count": exec_count,
            "total_disk_spill_mb": round(total_spill, 0),
            "avg_gc_pct": round(avg_gc, 1),
            "executors_with_spill": spill_execs,
            "recommendations": recommendations,
        }

    def get_parallelism_analysis(self, app_id: str) -> dict[str, Any]:
        """Analyze read/write/shuffle parallelism across stages.

        Returns empty dict if no parallelism issues detected.
        """
        stages = self.get_stage_performance(app_id)
        if not stages:
            return {}

        active = [
            s
            for s in stages
            if s.get("bottleneck_type") != "SKIPPED"
            and int(s.get("task_count", 0) or s.get("num_tasks", 0) or 0) > 0
        ]
        if not active:
            return {}

        issues: list[dict[str, Any]] = []

        for s in active:
            sid = s.get("stage_id", "")
            name = (s.get("stage_name", "") or "")[:40]
            tasks = int(s.get("task_count", 0) or s.get("num_tasks", 0) or 0)
            input_mb = float(s.get("input_mb", 0) or 0)
            output_mb = float(s.get("output_mb", 0) or 0)
            shuffle_read_mb = float(s.get("shuffle_read_mb", 0) or 0)

            if tasks <= 0:
                continue

            # Read parallelism
            if input_mb > 0:
                mb_per_task = input_mb / tasks
                if mb_per_task > 256:
                    issues.append(
                        {
                            "stage_id": sid,
                            "stage_name": name,
                            "type": "READ_LOW",
                            "severity": "MEDIUM",
                            "mb_per_task": round(mb_per_task),
                            "detail": f"tasks={tasks}, input={input_mb:.0f}MB, {mb_per_task:.0f}MB/task (>256MB)",
                            "recommendation": "Reduce maxPartitionBytes or increase partition count",
                        }
                    )
                elif mb_per_task < 1 and tasks > 100:
                    issues.append(
                        {
                            "stage_id": sid,
                            "stage_name": name,
                            "type": "READ_HIGH",
                            "severity": "LOW",
                            "mb_per_task": round(mb_per_task, 2),
                            "detail": f"tasks={tasks}, input={input_mb:.0f}MB, {mb_per_task:.2f}MB/task (<1MB)",
                            "recommendation": "Consolidate small files or use coalesce",
                        }
                    )

            # Write parallelism
            if output_mb > 0:
                mb_per_task_out = output_mb / tasks
                if mb_per_task_out > 256:
                    issues.append(
                        {
                            "stage_id": sid,
                            "stage_name": name,
                            "type": "WRITE_LOW",
                            "severity": "MEDIUM",
                            "mb_per_task": round(mb_per_task_out),
                            "detail": f"tasks={tasks}, output={output_mb:.0f}MB, {mb_per_task_out:.0f}MB/task (>256MB)",
                            "recommendation": "Use repartition to increase write parallelism",
                        }
                    )
                elif mb_per_task_out < 1 and tasks > 100:
                    issues.append(
                        {
                            "stage_id": sid,
                            "stage_name": name,
                            "type": "WRITE_HIGH",
                            "severity": "MEDIUM",
                            "mb_per_task": round(mb_per_task_out, 2),
                            "detail": f"tasks={tasks}, output={output_mb:.0f}MB, {mb_per_task_out:.2f}MB/task (<1MB)",
                            "recommendation": "Use coalesce to reduce small file output",
                        }
                    )

            # Shuffle parallelism
            if shuffle_read_mb > 0:
                mb_per_task_shuf = shuffle_read_mb / tasks
                if mb_per_task_shuf > 256:
                    issues.append(
                        {
                            "stage_id": sid,
                            "stage_name": name,
                            "type": "SHUFFLE_LOW",
                            "severity": "MEDIUM",
                            "mb_per_task": round(mb_per_task_shuf),
                            "detail": f"tasks={tasks}, shuffle_read={shuffle_read_mb:.0f}MB, {mb_per_task_shuf:.0f}MB/task (>256MB)",
                            "recommendation": "Increase spark.sql.shuffle.partitions",
                        }
                    )

        if not issues:
            return {}

        type_counts: dict[str, int] = {}
        for iss in issues:
            t = iss["type"]
            type_counts[t] = type_counts.get(t, 0) + 1

        # Sort by severity (MEDIUM first) then mb_per_task descending
        severity_order = {"MEDIUM": 0, "LOW": 1}
        sorted_issues = sorted(
            issues,
            key=lambda x: (
                severity_order.get(x.get("severity", "LOW"), 2),
                -(x.get("mb_per_task", 0)),
            ),
        )

        return {
            "issues": sorted_issues[:10],
            "total_issues": len(issues),
            "analyzed_stage_count": len(active),
            "total_stage_count": len(stages),
            "type_counts": type_counts,
            "worst_issues": sorted_issues[:3],
        }

    # SQL prefixes that indicate a rewritable SQL statement (Level 1 detection)
    _SQL_PREFIXES = ("SELECT", "INSERT", "MERGE", "WITH", "UPDATE", "DELETE", "CREATE", "REPLACE")

    def get_sql_plan_top_n(self, app_id: str, limit: int = 5) -> list[dict[str, Any]]:
        """Get top N heaviest SQL executions with plan analysis fields.

        Returns execution_id, duration, operator count, join breakdown,
        DataSourceInfo (scan_tables || scan_paths || description_short),
        and Type (SQL statement type or DataFrame).
        Photon columns are excluded (covered by Appendix A).
        """
        fqn = self._fqn("gold_sql_photon_analysis")
        safe_limit = int(limit)
        sql = f"""
            SELECT execution_id,
                   SUBSTRING(description_short, 1, 120) AS description_short,
                   ROUND(duration_sec, 1) AS duration_sec,
                   total_operators,
                   bhj_count,
                   photon_bhj_count,
                   smj_count,
                   total_join_count,
                   SUBSTRING(scan_tables, 1, 120) AS scan_tables,
                   SUBSTRING(scan_paths, 1, 120) AS scan_paths,
                   scan_column_count
            FROM {fqn}
            WHERE app_id = :app_id AND duration_sec IS NOT NULL
            ORDER BY duration_sec DESC
            LIMIT {safe_limit}
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parameters={"app_id": app_id})
                    columns = [desc[0] for desc in cursor.description]
                    rows = cursor.fetchall()
                    results = [dict(zip(columns, row)) for row in rows]

            # Post-process: add DataSourceInfo and Type
            for row in results:
                desc = (row.get("description_short") or "").strip()
                tables = (row.get("scan_tables") or "").strip()
                paths = (row.get("scan_paths") or "").strip()

                # DataSourceInfo: scan_tables > scan_paths > description_short
                if tables:
                    row["data_source_info"] = tables
                elif paths:
                    row["data_source_info"] = paths
                else:
                    row["data_source_info"] = desc[:100] if desc else ""

                # Type: detect SQL statement type or DataFrame
                upper = desc.upper()
                row["type"] = "DataFrame"
                for prefix in self._SQL_PREFIXES:
                    if upper.startswith(prefix):
                        # Extract statement type (e.g. "SELECT", "MERGE", "CREATE TABLE")
                        if upper.startswith("CREATE"):
                            row["type"] = "SQL (CTAS)"
                        else:
                            row["type"] = f"SQL ({prefix})"
                        break

                # Remove intermediate columns to keep LLM payload lean
                row.pop("scan_tables", None)
                row.pop("scan_paths", None)
                row.pop("description_short", None)

            return results
        except Exception:
            logger.exception("Failed to get SQL plan top %d for %s", safe_limit, app_id)
            return []

    # ------------------------------------------------------------------
    # Serialization analysis
    # ------------------------------------------------------------------

    def get_serialization_summary(self, app_id: str) -> dict[str, Any]:
        """Aggregate serialization metrics across all stages.

        Returns empty dict if serialization columns are not yet available
        (ETL re-run required to add deserialize_ms / result_serialize_ms).
        """
        fqn = self._fqn("gold_stage_performance")
        # First check if serialization columns exist (added by ETL v4.29+)
        check_sql = f"SELECT * FROM {fqn} WHERE app_id = :app_id LIMIT 1"
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(check_sql, parameters={"app_id": app_id})
                    col_names = {desc[0] for desc in cursor.description}
                    if "deserialize_ms" not in col_names:
                        logger.info("Serialization columns not yet in %s — ETL re-run needed", fqn)
                        return {}
        except Exception:
            logger.exception("Failed to check serialization columns in %s", fqn)
            return {}

        sql = f"""
            SELECT ROUND(SUM(COALESCE(deserialize_ms, 0)), 0) AS total_deserialize_ms,
                   ROUND(SUM(COALESCE(result_serialize_ms, 0)), 0) AS total_result_serialize_ms,
                   ROUND(SUM(COALESCE(deserialize_ms, 0)) + SUM(COALESCE(result_serialize_ms, 0)), 0) AS total_serialization_ms,
                   ROUND(SUM(COALESCE(duration_ms, 0)), 0) AS total_exec_run_ms,
                   ROUND(
                       CASE WHEN SUM(COALESCE(duration_ms, 0)) > 0
                            THEN (SUM(COALESCE(deserialize_ms, 0)) + SUM(COALESCE(result_serialize_ms, 0)))
                                 / SUM(COALESCE(duration_ms, 0)) * 100
                            ELSE 0 END, 1
                   ) AS serialization_pct,
                   SUM(CASE WHEN COALESCE(serialization_pct, 0) > 10 THEN 1 ELSE 0 END) AS stages_with_high_ser
            FROM {fqn}
            WHERE app_id = :app_id
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parameters={"app_id": app_id})
                    columns = [desc[0] for desc in cursor.description]
                    row = cursor.fetchone()
                    return dict(zip(columns, row)) if row else {}
        except Exception:
            logger.exception("Failed to get serialization summary for %s", app_id)
            return {}

    def get_high_serialization_jobs(self, app_id: str) -> list[dict[str, Any]]:
        """Get top jobs with high-serialization stages, joined via stage_ids.

        Returns empty list if serialization columns or job_detail not available.
        """
        stage_fqn = self._fqn("gold_stage_performance")
        job_fqn = self._fqn("gold_job_detail")
        sql = f"""
            WITH job_stages AS (
                SELECT j.job_id, j.sql_execution_id,
                       EXPLODE(FROM_JSON(j.stage_ids, 'ARRAY<INT>')) AS stage_id
                FROM {job_fqn} j
                WHERE j.app_id = :app_id
            )
            SELECT js.job_id, js.sql_execution_id,
                   s.stage_id, SUBSTRING(s.stage_name, 1, 60) AS stage_name,
                   ROUND(s.serialization_pct, 1) AS serialization_pct,
                   ROUND(s.deserialize_ms, 0) AS deserialize_ms,
                   ROUND(s.result_serialize_ms, 0) AS result_serialize_ms,
                   s.duration_ms, s.task_count
            FROM {stage_fqn} s
            JOIN job_stages js ON s.stage_id = js.stage_id
            WHERE s.app_id = :app_id AND s.serialization_pct > 10
            ORDER BY s.serialization_pct DESC
            LIMIT 5
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parameters={"app_id": app_id})
                    cols = [desc[0] for desc in cursor.description]
                    return [dict(zip(cols, row)) for row in cursor.fetchall()]
        except Exception:
            logger.exception("Failed to get high serialization jobs for %s", app_id)
            return []

    def get_udf_analysis(self, app_id: str) -> list[dict[str, Any]]:
        """Detect UDF types from SQL physical plans."""
        fqn = self._fqn("gold_sql_photon_analysis")
        sql = f"""
            SELECT execution_id,
                   SUBSTRING(description_short, 1, 80) AS description_short,
                   ROUND(duration_sec, 1) AS duration_sec,
                   non_photon_op_list
            FROM {fqn}
            WHERE app_id = :app_id
              AND (non_photon_op_list LIKE '%BatchEvalPython%'
                   OR non_photon_op_list LIKE '%ArrowEvalPython%'
                   OR non_photon_op_list LIKE '%FlatMapGroupsInPandas%'
                   OR non_photon_op_list LIKE '%ExistingRDD%')
            ORDER BY duration_sec DESC
            LIMIT 10
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parameters={"app_id": app_id})
                    columns = [desc[0] for desc in cursor.description]
                    rows = cursor.fetchall()
                    return [dict(zip(columns, row)) for row in rows]
        except Exception:
            logger.exception("Failed to get UDF analysis for %s", app_id)
            return []

    def get_skew_analysis(self, app_id: str) -> dict[str, Any]:
        """Analyze data skew: skewed stages + join SQL correlation.

        Returns empty dict if no DATA_SKEW stages found.
        """
        # 1. Skew stages (Top 5 by skew ratio)
        stage_fqn = self._fqn("gold_stage_performance")
        stage_sql = f"""
            SELECT stage_id, stage_name, duration_ms,
                   task_skew_ratio, shuffle_skew_ratio,
                   data_skew_gap_mb, data_skew_gap_p50_mb,
                   task_p50_ms, task_max_ms, task_count,
                   shuffle_read_mb, shuffle_write_mb
            FROM {stage_fqn}
            WHERE app_id = :app_id AND bottleneck_type = 'DATA_SKEW'
            ORDER BY task_skew_ratio DESC
            LIMIT 5
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(stage_sql, parameters={"app_id": app_id})
                    cols = [desc[0] for desc in cursor.description]
                    skew_stages = [dict(zip(cols, row)) for row in cursor.fetchall()]
        except Exception:
            logger.exception("Failed to get skew stages for %s", app_id)
            return {}

        if not skew_stages:
            return {}

        # 2. Join SQLs (Top 10 with joins, SMJ first)
        sql_fqn = self._fqn("gold_sql_photon_analysis")
        join_sql = f"""
            SELECT execution_id,
                   SUBSTRING(description_short, 1, 80) AS description_short,
                   ROUND(duration_sec, 1) AS duration_sec,
                   smj_count, bhj_count, photon_bhj_count, total_join_count
            FROM {sql_fqn}
            WHERE app_id = :app_id AND total_join_count > 0
            ORDER BY smj_count DESC, duration_sec DESC
            LIMIT 10
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(join_sql, parameters={"app_id": app_id})
                    cols = [desc[0] for desc in cursor.description]
                    join_sqls = [dict(zip(cols, row)) for row in cursor.fetchall()]
        except Exception:
            logger.exception("Failed to get join SQLs for %s", app_id)
            join_sqls = []

        # Summary
        max_ratio = max(float(s.get("task_skew_ratio", 0) or 0) for s in skew_stages)
        has_shuffle_skew = any(float(s.get("shuffle_skew_ratio", 0) or 0) > 5 for s in skew_stages)
        has_time_skew = any(float(s.get("task_skew_ratio", 0) or 0) > 5 for s in skew_stages)
        has_smj = any(int(s.get("smj_count", 0) or 0) > 0 for s in join_sqls)

        if has_shuffle_skew and has_time_skew:
            dominant = "both"
        elif has_shuffle_skew:
            dominant = "data"
        else:
            dominant = "time"

        return {
            "skew_stages": skew_stages,
            "join_sqls": join_sqls,
            "skew_summary": {
                "total_skew_stages": len(skew_stages),
                "max_skew_ratio": round(max_ratio, 1),
                "dominant_skew_type": dominant,
                "has_smj": has_smj,
            },
        }

    def get_driver_risk_analysis(self, app_id: str) -> dict[str, Any]:
        """Analyze driver-side risks: large result sizes, OOM failures, collect operators.

        Returns empty dict if no driver risks detected.
        Gracefully handles missing result_size_mb column (pre-ETL data).
        """
        stage_fqn = self._fqn("gold_stage_performance")

        # Check if result_size_mb column exists
        check_sql = f"SELECT * FROM {stage_fqn} WHERE app_id = :app_id LIMIT 1"
        has_result_size = False
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(check_sql, parameters={"app_id": app_id})
                    col_names = {desc[0] for desc in cursor.description}
                    has_result_size = "result_size_mb" in col_names
        except Exception:
            logger.exception("Failed to check driver risk columns in %s", stage_fqn)
            return {}

        # Query stages with large result sizes or OOM failures
        if has_result_size:
            stage_sql = f"""
                SELECT stage_id, stage_name,
                       ROUND(COALESCE(result_size_mb, 0), 2) AS total_result_size_mb,
                       task_count, failure_reason
                FROM {stage_fqn}
                WHERE app_id = :app_id
                  AND (COALESCE(result_size_mb, 0) > 10
                       OR failure_reason LIKE '%OutOfMemoryError%'
                       OR failure_reason LIKE '%GC overhead limit%')
                ORDER BY result_size_mb DESC
                LIMIT 10
            """
        else:
            stage_sql = f"""
                SELECT stage_id, stage_name,
                       0.0 AS total_result_size_mb,
                       task_count, failure_reason
                FROM {stage_fqn}
                WHERE app_id = :app_id
                  AND (failure_reason LIKE '%OutOfMemoryError%'
                       OR failure_reason LIKE '%GC overhead limit%')
                LIMIT 10
            """

        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(stage_sql, parameters={"app_id": app_id})
                    cols = [desc[0] for desc in cursor.description]
                    risk_stages = [dict(zip(cols, row)) for row in cursor.fetchall()]
        except Exception:
            logger.exception("Failed to get driver risk stages for %s", app_id)
            return {}

        # Collect operators from SQL plans
        sql_fqn = self._fqn("gold_sql_photon_analysis")
        collect_sql = f"""
            SELECT execution_id,
                   SUBSTRING(description_short, 1, 80) AS description_short,
                   ROUND(duration_sec, 1) AS duration_sec,
                   non_photon_op_list
            FROM {sql_fqn}
            WHERE app_id = :app_id
              AND (non_photon_op_list LIKE '%CollectLimit%'
                   OR non_photon_op_list LIKE '%LocalLimit%'
                   OR non_photon_op_list LIKE '%TakeOrderedAndProject%')
            ORDER BY duration_sec DESC
            LIMIT 5
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(collect_sql, parameters={"app_id": app_id})
                    cols = [desc[0] for desc in cursor.description]
                    collect_ops = [dict(zip(cols, row)) for row in cursor.fetchall()]
        except Exception:
            logger.exception("Failed to get collect operators for %s", app_id)
            collect_ops = []

        if not risk_stages and not collect_ops:
            return {}

        # Summarize
        oom_stages = sum(
            1
            for s in risk_stages
            if s.get("failure_reason") and "OutOfMemoryError" in str(s["failure_reason"])
        )
        total_result_mb = sum(float(s.get("total_result_size_mb", 0) or 0) for s in risk_stages)
        large_result_stages = sum(
            1 for s in risk_stages if float(s.get("total_result_size_mb", 0) or 0) > 10
        )

        return {
            "risk_stages": risk_stages,
            "collect_operators": collect_ops,
            "oom_stages": oom_stages,
            "total_result_size_mb": round(total_result_mb, 2),
            "large_result_stages": large_result_stages,
        }

    # ------------------------------------------------------------------
    # Streaming queries
    # ------------------------------------------------------------------

    def get_streaming_query_summary(self, app_id: str) -> list[dict[str, Any]]:
        """Get streaming query summaries for a given app_id."""
        return self._query_table("gold_streaming_query_summary", app_id=app_id)

    def get_streaming_batch_detail(
        self, app_id: str, query_id: str | None = None
    ) -> list[dict[str, Any]]:
        """Get streaming batch detail. Optionally filter by query_id."""
        if query_id is None:
            return self._query_table("gold_streaming_batch_detail", app_id=app_id)

        fqn = self._fqn("gold_streaming_batch_detail")
        sql = (
            f"SELECT * FROM {fqn} WHERE app_id = :app_id AND query_id = :query_id ORDER BY batch_id"
        )
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parameters={"app_id": app_id, "query_id": query_id})
                    columns = [desc[0] for desc in cursor.description]
                    rows = cursor.fetchall()
                    return [dict(zip(columns, row)) for row in rows]
        except Exception:
            logger.exception("Failed to query %s for query_id=%s", fqn, query_id)
            return []

    def get_streaming_summary(self, app_id: str) -> dict[str, Any]:
        """Composite: aggregate streaming metrics for LLM Fact Pack."""
        queries = self.get_streaming_query_summary(app_id)
        if not queries:
            return {}

        query_count = len(queries)
        total_batches = sum(int(q.get("total_batches", 0) or 0) for q in queries)
        stateful_count = sum(1 for q in queries if q.get("is_stateful") in (True, "true", 1))
        has_exceptions = any(q.get("exception") is not None for q in queries)

        avg_durations = [float(q.get("avg_batch_duration_ms", 0) or 0) for q in queries]
        max_durations = [float(q.get("max_batch_duration_ms", 0) or 0) for q in queries]
        throughputs = [float(q.get("avg_processed_rows_per_sec", 0) or 0) for q in queries]
        state_mems = [float(q.get("max_state_memory_bytes", 0) or 0) for q in queries]

        # Bottleneck counts
        bn_counts: dict[str, int] = {}
        for q in queries:
            bt = q.get("bottleneck_type", "STREAM_OK")
            bn_counts[bt] = bn_counts.get(bt, 0) + 1

        source_types = list({q.get("source_type", "Unknown") for q in queries})
        sink_types = list({q.get("sink_type", "Unknown") for q in queries})

        return {
            "query_count": query_count,
            "total_batches": total_batches,
            "stateful_query_count": stateful_count,
            "has_exceptions": has_exceptions,
            "avg_batch_duration_ms": round(sum(avg_durations) / len(avg_durations), 1)
            if avg_durations
            else 0,
            "max_batch_duration_ms": max(max_durations) if max_durations else 0,
            "avg_throughput_rows_per_sec": round(sum(throughputs) / len(throughputs), 1)
            if throughputs
            else 0,
            "max_state_memory_bytes": max(state_mems) if state_mems else 0,
            "bottleneck_counts": bn_counts,
            "source_types": source_types,
            "sink_types": sink_types,
        }

    def get_streaming_bottleneck_summary(self, app_id: str) -> list[dict[str, Any]]:
        """Aggregate streaming bottleneck counts by type and severity."""
        queries = self.get_streaming_query_summary(app_id)
        summary: dict[str, dict] = {}
        for q in queries:
            bt = q.get("bottleneck_type", "STREAM_OK")
            sev = q.get("severity", "NONE")
            if bt not in summary:
                summary[bt] = {"bottleneck_type": bt, "count": 0, "max_severity": sev}
            summary[bt]["count"] += 1
            sev_rank = {"CRITICAL": 4, "HIGH": 3, "MEDIUM": 2, "LOW": 1, "NONE": 0}
            if sev_rank.get(sev, 0) > sev_rank.get(summary[bt]["max_severity"], 0):
                summary[bt]["max_severity"] = sev
        return list(summary.values())

    def get_streaming_idle_events(self, app_id: str) -> list[dict[str, Any]]:
        """Get QueryIdleEvent timestamps for trigger interval estimation."""
        fqn = self._fqn("silver_streaming_events")
        sql = (
            f"SELECT event_timestamp FROM {fqn} "
            "WHERE app_id = :app_id AND event_type LIKE '%QueryIdleEvent%' "
            "ORDER BY event_timestamp"
        )
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parameters={"app_id": app_id})
                    columns = [desc[0] for desc in cursor.description]
                    rows = cursor.fetchall()
                    return [dict(zip(columns, row)) for row in rows]
        except Exception:
            logger.exception("Failed to query idle events for %s", app_id)
            return []

    def get_streaming_deep_analysis(self, app_id: str) -> dict[str, Any]:
        """Deep streaming analysis: state growth and watermark progression.

        Returns empty dict if no streaming batch data found.
        """
        fqn = self._fqn("gold_streaming_batch_detail")
        sql = f"""
            SELECT query_id, batch_id,
                   COALESCE(state_memory_used_bytes, 0) AS state_memory_used_bytes,
                   COALESCE(state_num_rows_total, 0) AS state_num_rows_total,
                   COALESCE(state_rows_dropped_by_watermark, 0) AS state_rows_dropped_by_watermark,
                   watermark
            FROM {fqn}
            WHERE app_id = :app_id
            ORDER BY query_id, batch_id
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parameters={"app_id": app_id})
                    cols = [desc[0] for desc in cursor.description]
                    rows = [dict(zip(cols, row)) for row in cursor.fetchall()]
        except Exception:
            logger.exception("Failed to get streaming deep analysis for %s", app_id)
            return {}

        if not rows:
            return {}

        # State growth analysis
        stateful_rows = [r for r in rows if float(r.get("state_memory_used_bytes", 0) or 0) > 0]
        state_growth: dict[str, Any] = {}
        if stateful_rows:
            first_mem = float(stateful_rows[0].get("state_memory_used_bytes", 0) or 0)
            last_mem = float(stateful_rows[-1].get("state_memory_used_bytes", 0) or 0)
            n = len(stateful_rows)
            growth_per_batch = (last_mem - first_mem) / max(n - 1, 1) if n > 1 else 0
            total_dropped = sum(
                int(r.get("state_rows_dropped_by_watermark", 0) or 0) for r in stateful_rows
            )
            total_rows = int(stateful_rows[-1].get("state_num_rows_total", 0) or 0)
            # eviction_ratio = dropped / (state + dropped) — proportion of all processed rows that were evicted
            eviction_ratio = total_dropped / max(total_rows + total_dropped, 1)

            state_growth = {
                "first_state_mb": round(first_mem / 1024 / 1024, 2),
                "last_state_mb": round(last_mem / 1024 / 1024, 2),
                "growth_mb_per_batch": round(growth_per_batch / 1024 / 1024, 4),
                "batches_analyzed": n,
                "total_rows_dropped_by_watermark": total_dropped,
                "last_state_rows": total_rows,
                "eviction_ratio": round(eviction_ratio, 4),
            }

        # Watermark progression
        watermarks = [r.get("watermark") for r in rows if r.get("watermark")]
        watermark_info: dict[str, Any] = {}
        if watermarks:
            watermark_info = {
                "first_watermark": str(watermarks[0]),
                "last_watermark": str(watermarks[-1]),
                "total_watermark_updates": len(watermarks),
            }

        if not state_growth and not watermark_info:
            return {}

        result: dict[str, Any] = {}
        if state_growth:
            result["state_growth"] = state_growth
        if watermark_info:
            result["watermark"] = watermark_info
        return result

    def get_scan_metrics_summary(self, app_id: str) -> dict[str, Any]:
        """Aggregate scan metrics (cache hit, pruning, cloud I/O) from sql_photon."""
        fqn = self._fqn("gold_sql_photon_analysis")
        sql = f"""
            SELECT ROUND(AVG(cache_hit_pct), 1) AS avg_cache_hit_pct,
                   ROUND(SUM(cache_hit_bytes) / 1024.0 / 1024.0 / 1024.0, 2) AS total_cache_hit_gb,
                   ROUND(SUM(cache_miss_bytes) / 1024.0 / 1024.0 / 1024.0, 2) AS total_cache_miss_gb,
                   ROUND(AVG(file_pruning_pct), 1) AS avg_file_pruning_pct,
                   SUM(files_read) AS total_files_read,
                   SUM(files_pruned) AS total_files_pruned,
                   ROUND(SUM(files_read_size_mb) / 1024.0, 2) AS total_files_read_gb,
                   ROUND(SUM(scan_time_ms) / 1000.0, 1) AS total_scan_time_sec,
                   SUM(cloud_request_count) AS total_cloud_requests,
                   ROUND(SUM(cloud_request_dur_ms) / 1000.0, 1) AS total_cloud_request_sec
            FROM {fqn}
            WHERE app_id = :app_id AND (cache_hit_pct IS NOT NULL OR files_read > 0)
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parameters={"app_id": app_id})
                    columns = [desc[0] for desc in cursor.description]
                    row = cursor.fetchone()
                    return dict(zip(columns, row)) if row else {}
        except Exception:
            logger.exception("Failed to get scan metrics summary")
            return {}

    def get_io_top5(self, app_id: str) -> list[dict[str, Any]]:
        """Get top 5 scan sources by read size with column count."""
        fqn = self._fqn("gold_sql_photon_analysis")
        sql = f"""
            SELECT scan_tables, scan_formats, scan_paths,
                   scan_column_count, scan_filters,
                   ROUND(cache_hit_pct, 1) AS cache_hit_pct,
                   files_read, files_pruned,
                   ROUND(file_pruning_pct, 1) AS file_pruning_pct,
                   ROUND(files_read_size_mb, 1) AS files_read_size_mb,
                   cloud_request_count,
                   ROUND(duration_sec, 1) AS query_duration_sec,
                   execution_id
            FROM {fqn}
            WHERE app_id = :app_id AND files_read_size_mb IS NOT NULL AND files_read_size_mb > 0
            ORDER BY files_read_size_mb DESC
            LIMIT 5
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parameters={"app_id": app_id})
                    columns = [desc[0] for desc in cursor.description]
                    rows = cursor.fetchall()
                    return [dict(zip(columns, row)) for row in rows]
        except Exception:
            logger.exception("Failed to get I/O top 5")
            return []

    def get_duplicate_scans(self, app_id: str) -> list[dict[str, Any]]:
        """Detect duplicate scans (same table scanned multiple times)."""
        fqn = self._fqn("gold_sql_photon_analysis")
        sql = f"""
            SELECT scan_tables, scan_formats,
                   MAX(scan_paths) AS scan_paths,
                   MAX(scan_column_count) AS max_column_count,
                   COUNT(*) AS scan_count,
                   ROUND(SUM(duration_sec), 1) AS total_duration_sec
            FROM {fqn}
            WHERE app_id = :app_id AND scan_tables IS NOT NULL AND scan_tables != ''
            GROUP BY scan_tables, scan_formats
            HAVING COUNT(*) >= 2
            ORDER BY scan_count DESC
            LIMIT 5
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parameters={"app_id": app_id})
                    columns = [desc[0] for desc in cursor.description]
                    rows = cursor.fetchall()
                    return [dict(zip(columns, row)) for row in rows]
        except Exception:
            logger.exception("Failed to get duplicate scans")
            return []

    # ------------------------------------------------------------------
    # Write methods (for app-side report generation)
    # ------------------------------------------------------------------

    def write_narrative_summary(
        self,
        app_id: str,
        model_name: str,
        output_lang: str,
        summary_text: str,
        job_analysis_text: str,
        node_analysis_text: str,
        top3_text: str,
        prompt_tokens: int,
        total_tokens: int,
        experiment_id: str = "",
        variant: str = "",
    ) -> bool:
        """Write LLM narrative to gold_narrative_summary via SQL MERGE.

        Returns True on success. Cost is stored in gold_application_summary
        (ETL-computed) and no longer duplicated here (deprecated in v5.12).
        """
        fqn = self._fqn("gold_narrative_summary")
        # Ensure table exists
        create_ddl = f"""
            CREATE TABLE IF NOT EXISTS {fqn} (
                generated_at       TIMESTAMP,
                app_id             STRING,
                model_name         STRING,
                schema_name        STRING,
                output_lang        STRING,
                summary_text       STRING,
                job_analysis_text  STRING,
                node_analysis_text STRING,
                top3_text          STRING,
                prompt_tokens      INT,
                total_tokens       INT,
                experiment_id      STRING,
                variant            STRING
            )
            USING DELTA
        """
        merge_sql = f"""
            MERGE INTO {fqn} AS t
            USING (SELECT
                CURRENT_TIMESTAMP() AS generated_at,
                :app_id AS app_id,
                :model_name AS model_name,
                :schema_name AS schema_name,
                :output_lang AS output_lang,
                :summary_text AS summary_text,
                :job_analysis_text AS job_analysis_text,
                :node_analysis_text AS node_analysis_text,
                :top3_text AS top3_text,
                :prompt_tokens AS prompt_tokens,
                :total_tokens AS total_tokens,
                :experiment_id AS experiment_id,
                :variant AS variant
            ) AS s
            ON t.app_id = s.app_id
            WHEN MATCHED THEN UPDATE SET
                t.generated_at       = s.generated_at,
                t.model_name         = s.model_name,
                t.schema_name        = s.schema_name,
                t.output_lang        = s.output_lang,
                t.summary_text       = s.summary_text,
                t.job_analysis_text  = s.job_analysis_text,
                t.node_analysis_text = s.node_analysis_text,
                t.top3_text          = s.top3_text,
                t.prompt_tokens      = s.prompt_tokens,
                t.total_tokens       = s.total_tokens,
                t.experiment_id      = s.experiment_id,
                t.variant            = s.variant
            WHEN NOT MATCHED THEN INSERT *
        """
        params = {
            "app_id": app_id,
            "model_name": model_name,
            "schema_name": f"{self._config.catalog}.{self._config.schema}",
            "output_lang": output_lang,
            "summary_text": summary_text,
            "job_analysis_text": job_analysis_text,
            "node_analysis_text": node_analysis_text,
            "top3_text": top3_text,
            "prompt_tokens": prompt_tokens,
            "total_tokens": total_tokens,
            "experiment_id": experiment_id or None,
            "variant": variant or None,
        }
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(create_ddl)
                    # Best-effort migration: drop deprecated estimated_cost_usd column.
                    # Requires Delta column mapping — skipped silently if unsupported.
                    try:
                        cursor.execute(f"DESCRIBE TABLE {fqn}")
                        existing = {row[0].lower() for row in cursor.fetchall()}
                        if "estimated_cost_usd" in existing:
                            logger.info(
                                "Dropping deprecated column estimated_cost_usd from %s", fqn
                            )
                            cursor.execute(
                                f"ALTER TABLE {fqn} "
                                f"SET TBLPROPERTIES ("
                                f"'delta.columnMapping.mode' = 'name', "
                                f"'delta.minReaderVersion' = '2', "
                                f"'delta.minWriterVersion' = '5')"
                            )
                            cursor.execute(f"ALTER TABLE {fqn} DROP COLUMN estimated_cost_usd")
                    except Exception:
                        logger.debug(
                            "Deprecated column drop skipped for %s (safe to ignore)",
                            fqn,
                            exc_info=True,
                        )
                    cursor.execute(merge_sql, parameters=params)
            logger.info("Narrative written for app_id=%s", app_id)
            return True
        except Exception:
            logger.exception("Failed to write narrative summary for app_id=%s", app_id)
            return False

    def get_narrative_summary(self, app_id: str | None = None) -> dict[str, Any] | None:
        """Get the latest LLM-generated narrative summary (up to 4 sections).

        Args:
            app_id: Optional application ID to filter by. If None, returns the
                    latest narrative summary across all applications.
        """
        fqn = self._fqn("gold_narrative_summary")
        params: dict[str, Any] = {}
        where = ""
        if app_id:
            where = "WHERE app_id = :app_id"
            params["app_id"] = app_id
        sql = f"""
            SELECT *
            FROM {fqn}
            {where}
            ORDER BY generated_at DESC
            LIMIT 1
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parameters=params if params else None)
                    row = cursor.fetchone()
                    if row is None:
                        return None
                    columns = [desc[0] for desc in cursor.description]
                    return dict(zip(columns, row))
        except Exception:
            logger.exception("Failed to get narrative summary from %s", fqn)
            return None

    def list_applications_for_compare(
        self,
        cluster_id: str | None = None,
        experiment_id: str | None = None,
        variant: str | None = None,
    ) -> list[dict[str, Any]]:
        """List applications for comparison selection.

        Returns a compact list of apps with key metrics, optionally
        filtered by cluster_id, experiment_id, and/or variant.
        """
        fqn_app = self._fqn("gold_application_summary")
        fqn_nar = self._fqn("gold_narrative_summary")
        where = "WHERE n.app_id IS NOT NULL"
        params: dict[str, Any] = {}
        if cluster_id:
            where += " AND a.cluster_id = :cluster_id"
            params["cluster_id"] = cluster_id
        if experiment_id:
            where += " AND n.experiment_id = :experiment_id"
            params["experiment_id"] = experiment_id
        if variant:
            where += " AND n.variant = :variant"
            params["variant"] = variant

        fqn_bn = self._fqn("gold_bottleneck_report")
        sql = f"""
            SELECT a.app_id, a.cluster_id, a.app_name,
                   n.generated_at AS analyzed_at,
                   n.experiment_id, n.variant, n.output_lang,
                   a.duration_ms, a.duration_min,
                   a.total_shuffle_gb, a.total_spill_gb,
                   a.worker_node_type, a.min_workers, a.max_workers,
                   a.total_jobs, a.job_success_rate,
                   a.total_input_gb, a.gc_overhead_pct,
                   a.dbr_version, a.cluster_availability,
                   COALESCE(b.bottleneck_count, 0) AS bottleneck_count,
                   a.estimated_total_usd AS estimated_cost_usd
            FROM {fqn_app} a
            INNER JOIN {fqn_nar} n ON a.app_id = n.app_id
            LEFT JOIN (
                SELECT app_id, COUNT(*) AS bottleneck_count
                FROM {fqn_bn}
                WHERE severity IN ('HIGH', 'MEDIUM')
                GROUP BY app_id
            ) b ON a.app_id = b.app_id
            {where}
            ORDER BY n.generated_at DESC
            LIMIT 200
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parameters=params if params else None)
                    columns = [desc[0] for desc in cursor.description]
                    rows = cursor.fetchall()
                    return [dict(zip(columns, row)) for row in rows]
        except Exception:
            logger.exception("Failed to list applications for compare")
            return []

    def get_stage_aggregates(self, app_id: str) -> dict[str, float]:
        """Get aggregated stage metrics for comparison.

        Queries gold_stage_performance and computes:
        - max_task_skew_ratio: max skew across all stages
        - avg_cpu_efficiency_pct: average CPU efficiency
        - total_disk_spill_mb: sum of disk spill
        - total_shuffle_read_mb: sum of shuffle reads
        - bottleneck_count: count of stages with a non-empty bottleneck_type
        """
        stages = self.get_stage_performance(app_id)
        if not stages:
            return {
                "max_task_skew_ratio": 0.0,
                "avg_cpu_efficiency_pct": 0.0,
                "total_disk_spill_mb": 0.0,
                "total_shuffle_read_mb": 0.0,
                "bottleneck_count": 0.0,
            }

        from core.spark_comparison import _aggregate_stages

        return _aggregate_stages(stages)

    def count_applications(self) -> int:
        """Count total applications."""
        fqn_app = self._fqn("gold_application_summary")
        sql = f"SELECT COUNT(*) FROM {fqn_app}"
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql)
                    row = cursor.fetchone()
                    return row[0] if row else 0
        except Exception:
            logger.exception("Failed to count applications")
            return 0

    def list_applications(self, page: int = 1, page_size: int = 20) -> list[dict[str, Any]]:
        """List applications with pagination.

        Tries to JOIN with narrative summary for output_lang column.
        Falls back to app summary only if narrative table doesn't exist.
        """
        page = max(1, int(page))
        page_size = max(1, min(100, int(page_size)))
        fqn_app = self._fqn("gold_application_summary")
        fqn_nar = self._fqn("gold_narrative_summary")
        offset = (page - 1) * page_size

        sql_with_join = f"""
            SELECT a.app_id, a.app_name, a.cluster_id, a.start_ts, a.duration_min,
                   a.total_jobs, a.job_success_rate, a.total_shuffle_gb, a.total_spill_gb,
                   n.output_lang, n.experiment_id, n.variant,
                   a.etl_loaded_at,
                   n.generated_at AS report_created_at,
                   CASE
                     WHEN n.generated_at IS NULL THEN 'NO_REPORT'
                     WHEN a.etl_loaded_at IS NOT NULL AND n.generated_at < a.etl_loaded_at THEN 'STALE'
                     ELSE 'CURRENT'
                   END AS report_status
            FROM {fqn_app} a
            LEFT JOIN {fqn_nar} n ON a.app_id = n.app_id
            ORDER BY a.start_ts DESC
            LIMIT {int(page_size)} OFFSET {int(offset)}
        """
        sql_without_join = f"""
            SELECT app_id, app_name, cluster_id, start_ts, duration_min,
                   total_jobs, job_success_rate, total_shuffle_gb, total_spill_gb,
                   NULL AS output_lang, NULL AS experiment_id, NULL AS variant,
                   NULL AS etl_loaded_at,
                   NULL AS report_created_at,
                   'NO_REPORT' AS report_status
            FROM {fqn_app}
            ORDER BY start_ts DESC
            LIMIT {int(page_size)} OFFSET {int(offset)}
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    try:
                        cursor.execute(sql_with_join)
                    except Exception:
                        logger.info("Narrative table not available, listing without output_lang")
                        cursor.execute(sql_without_join)
                    columns = [desc[0] for desc in cursor.description]
                    rows = cursor.fetchall()
                    return [dict(zip(columns, row)) for row in rows]
        except Exception:
            logger.exception("Failed to list applications")
            return []

    # -----------------------------------------------------------------------
    # Compare result history
    # -----------------------------------------------------------------------

    def list_compare_results(self, limit: int = 50) -> list[dict[str, Any]]:
        """List past Spark comparison results (without report_markdown)."""
        fqn = self._fqn("spark_compare_result")
        sql = f"""
            SELECT
                comparison_id, compared_at,
                baseline_analyzed_at, baseline_app_id,
                baseline_experiment, baseline_variant,
                baseline_duration_ms, baseline_alerts,
                candidate_analyzed_at, candidate_app_id,
                candidate_experiment, candidate_variant,
                candidate_duration_ms, candidate_alerts,
                regression_detected, regression_severity, net_score
            FROM {fqn}
            ORDER BY compared_at DESC
            LIMIT {limit}
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql)
                    rows = cursor.fetchall()
                    columns = [desc[0] for desc in cursor.description]
                    return [dict(zip(columns, row)) for row in rows]
        except Exception:
            logger.exception("Failed to list spark compare results")
            return []

    def get_compare_result(self, comparison_id: str) -> dict[str, Any] | None:
        """Load a single Spark compare result including report_markdown."""
        fqn = self._fqn("spark_compare_result")
        sql = f"""
            SELECT * FROM {fqn}
            WHERE comparison_id = :comparison_id
            LIMIT 1
        """
        try:
            with self._get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parameters={"comparison_id": comparison_id})
                    row = cursor.fetchone()
                    if row is None:
                        return None
                    columns = [desc[0] for desc in cursor.description]
                    return dict(zip(columns, row))
        except Exception:
            logger.exception("Failed to load spark compare result: %s", comparison_id)
            return None
