#!/bin/bash
# Wipe the deployed state for a target and reset locally generated files,
# so you can run a fresh `./scripts/deploy.sh` from a clean slate.
#
# Usage:
#   ./scripts/reset.sh              # soft reset (dev target)
#   ./scripts/reset.sh staging      # soft reset for a specific target
#   ./scripts/reset.sh dev --hard   # also resets dabs/local-overrides.yml
#                                   # to the sample (your edits will be lost)
#
# What "soft reset" does:
#   - databricks bundle destroy -t <target>   (removes app, jobs, permissions)
#   - rm dabs/app/runtime-config.json         (regenerated by deploy.sh)
#   - rm dabs/app/app.yaml                    (regenerated by deploy.sh)
#   - rm -rf dabs/.databricks                 (local bundle terraform state)
#
# What "--hard" adds:
#   - Restores dabs/local-overrides.yml from the sample
#     (you'll have to re-edit it with your catalog / warehouse / profile)
#
# What this script does NOT touch:
#   - The Unity Catalog catalog you created in the UI
#   - Existing schemas / tables / data
#   - Your ~/.databrickscfg auth profiles

set -euo pipefail

TARGET="${1:-dev}"
HARD=false
[ "${2:-}" = "--hard" ] && HARD=true

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

echo "=== Reset deploy state for target: ${TARGET} ==="
echo "This will:"
echo "  - databricks bundle destroy -t ${TARGET}  (removes app, jobs)"
echo "  - Remove dabs/app/runtime-config.json"
echo "  - Remove dabs/app/app.yaml"
echo "  - Remove dabs/.databricks/"
if $HARD; then
    echo "  - Reset dabs/local-overrides.yml from sample (your edits WILL BE LOST)"
fi
echo ""
echo "Not affected: Unity Catalog catalogs/schemas/data, ~/.databrickscfg profiles"
echo ""
read -p "Continue? [y/N] " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
fi

echo ""
echo "=== 1. Destroying bundle resources ==="
if [ -f "${ROOT_DIR}/dabs/local-overrides.yml" ]; then
    (cd "${ROOT_DIR}/dabs" && databricks bundle destroy -t "${TARGET}" --auto-approve) \
        && echo "  ✓ Bundle destroyed" \
        || echo "  ⚠ Bundle destroy failed or nothing to destroy — continuing"
else
    echo "  ⏭ Skipped (no dabs/local-overrides.yml to tell us which workspace)"
fi

echo ""
echo "=== 2. Removing generated files ==="
rm -f "${ROOT_DIR}/dabs/app/runtime-config.json" && echo "  ✓ Removed dabs/app/runtime-config.json" || true
rm -f "${ROOT_DIR}/dabs/app/app.yaml"            && echo "  ✓ Removed dabs/app/app.yaml"            || true
rm -rf "${ROOT_DIR}/dabs/.databricks"            && echo "  ✓ Removed dabs/.databricks/"            || true

if $HARD; then
    echo ""
    echo "=== 3. Resetting local-overrides.yml from sample ==="
    cp "${ROOT_DIR}/dabs/local-overrides.yml.sample" "${ROOT_DIR}/dabs/local-overrides.yml"
    echo "  ✓ Overwrote dabs/local-overrides.yml — re-edit with your values"
fi

echo ""
echo "=== ✓ Reset complete ==="
echo ""
echo "Next steps:"
echo "  1. Review / edit dabs/local-overrides.yml"
echo "  2. ./scripts/deploy.sh ${TARGET}"
