"""
Core module for Databricks SQL Query Profile Analyzer.

This module contains shared logic for both CLI and Web interfaces.
"""

from .analyzers import (
    analyze_from_dict,
    analyze_profile,
    calculate_bottleneck_indicators,
    enhance_bottleneck_with_explain,
    extract_hot_operators,
    generate_action_cards,
)
from .constants import THRESHOLDS, JoinType, Severity, UsageType
from .dbsql_cost import CostEstimate, SizeReferenceCost, estimate_query_cost, format_cost_usd
from .evidence import (
    EvidenceBudget,
    EvidenceBundle,
    EvidenceItem,
    EvidenceLocator,
    EvidenceSnippet,
    EvidenceSource,
    build_evidence,
    format_evidence_for_prompt,
)
from .explain_parser import (
    ExplainExtended,
    ExplainNode,
    ExplainSection,
    NodeFamily,
    PlanKind,
    parse_explain_extended,
)
from .extractors import (
    classify_join_type,
    compute_batch_statistics,
    extract_endpoint_id,
    extract_join_info,
    extract_node_metrics,
    extract_query_metrics,
    extract_shuffle_metrics,
    extract_sql_analysis,
    extract_streaming_context,
    extract_table_scan_metrics,
    is_streaming_profile,
)
from .i18n import (
    get_language,
    get_stage_messages,
    gettext,
    init_language_from_env,
    ngettext,
    set_language,
)
from .llm import (
    LLMError,
    LLMRateLimitError,
    LLMServiceError,
    LLMTimeoutError,
    analyze_with_llm,
    create_analysis_prompt,
    create_clustering_prompt,
    create_structured_analysis_prompt,
    create_structured_system_prompt,
    create_system_prompt,
    load_tuning_knowledge,
    parse_llm_sections,
    recommend_clustering_with_llm,
    refine_report_with_llm,
    refine_with_llm,
    review_report_with_llm,
    review_with_llm,
)
from .models import (
    ActionCard,
    Alert,
    BottleneckIndicators,
    CloudStorageMetrics,
    ClusteringRecommendation,
    ColumnReference,
    HashResizeHotspot,
    JoinInfo,
    MicroBatchMetrics,
    NodeMetrics,
    OperatorHotspot,
    PhotonBlocker,
    ProfileAnalysis,
    QueryMetrics,
    QueryStructure,
    ShuffleMetrics,
    SpillOperatorInfo,
    SQLAnalysis,
    StreamingContext,
    TableReference,
    TableScanMetrics,
)
from .reporters import (
    generate_alerts_section,
    generate_aqe_shuffle_section,
    generate_bottleneck_summary,
    generate_cloud_storage_section,
    generate_data_flow_section,
    generate_explain_section,
    generate_hot_operators_section,
    generate_io_metrics_section,
    generate_performance_metrics,
    generate_photon_blockers_section,
    generate_query_overview,
    generate_report,
    generate_report_legacy,
    generate_rule_based_recommendations,
    generate_rule_based_summary,
    generate_spill_analysis_section,
    generate_sql_section,
    generate_stage_execution_section,
    generate_validation_checklist,
    generate_warehouse_section,
)
from .sql_analyzer import analyze_sql, analyze_structure, extract_tables, format_sql
from .usecases import LLMConfig, PipelineOptions, PipelineResult, run_analysis_pipeline
from .utils import format_bytes, format_time_ms
from .warehouse_client import WarehouseClient, WarehouseInfo

__all__ = [
    # Constants
    "JoinType",
    "Severity",
    "THRESHOLDS",
    "UsageType",
    # Cost Estimation
    "CostEstimate",
    "SizeReferenceCost",
    "estimate_query_cost",
    "format_cost_usd",
    # Evidence
    "EvidenceBudget",
    "EvidenceBundle",
    "EvidenceItem",
    "EvidenceLocator",
    "EvidenceSnippet",
    "EvidenceSource",
    "build_evidence",
    "format_evidence_for_prompt",
    # Models
    "ActionCard",
    "Alert",
    "BottleneckIndicators",
    "CloudStorageMetrics",
    "ClusteringRecommendation",
    "ColumnReference",
    "JoinInfo",
    "MicroBatchMetrics",
    "NodeMetrics",
    "OperatorHotspot",
    "PhotonBlocker",
    "ProfileAnalysis",
    "QueryMetrics",
    "QueryStructure",
    "ShuffleMetrics",
    "SpillOperatorInfo",
    "SQLAnalysis",
    "StreamingContext",
    "TableReference",
    "TableScanMetrics",
    # Utils
    "format_bytes",
    "format_time_ms",
    # Extractors
    "classify_join_type",
    "compute_batch_statistics",
    "extract_endpoint_id",
    "extract_join_info",
    "extract_node_metrics",
    "extract_query_metrics",
    "extract_shuffle_metrics",
    "extract_sql_analysis",
    "extract_streaming_context",
    "extract_table_scan_metrics",
    "is_streaming_profile",
    # SQL Analyzer
    "analyze_sql",
    "analyze_structure",
    "extract_tables",
    "format_sql",
    # Analyzers
    "analyze_from_dict",
    "analyze_profile",
    "calculate_bottleneck_indicators",
    "enhance_bottleneck_with_explain",
    "extract_hot_operators",
    "generate_action_cards",
    # Explain Parser
    "ExplainExtended",
    "ExplainNode",
    "ExplainSection",
    "NodeFamily",
    "PlanKind",
    "parse_explain_extended",
    # LLM
    "LLMError",
    "LLMRateLimitError",
    "LLMServiceError",
    "LLMTimeoutError",
    "analyze_with_llm",
    "create_analysis_prompt",
    "create_clustering_prompt",
    "create_system_prompt",
    "load_tuning_knowledge",
    "recommend_clustering_with_llm",
    "refine_report_with_llm",
    "refine_with_llm",
    "review_report_with_llm",
    "review_with_llm",
    # Reporters
    "generate_alerts_section",
    "generate_aqe_shuffle_section",
    "generate_bottleneck_summary",
    "generate_cloud_storage_section",
    "generate_explain_section",
    "generate_hot_operators_section",
    "generate_io_metrics_section",
    "generate_photon_blockers_section",
    "generate_report",
    "generate_spill_analysis_section",
    "generate_sql_section",
    "generate_validation_checklist",
    "generate_warehouse_section",
    # i18n
    "get_language",
    "get_stage_messages",
    "gettext",
    "init_language_from_env",
    "ngettext",
    "set_language",
    # Usecases
    "LLMConfig",
    "PipelineOptions",
    "PipelineResult",
    "run_analysis_pipeline",
    # Warehouse Client
    "WarehouseClient",
    "WarehouseInfo",
]
